version: '3'

services:
  charge-factory-main:
    image: chargefactoryapp:0.0.1
    container_name: charge-factory
    environment:
      MESSAGE_DB_HOST: db
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    container_name: charge-factory_db
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: charge_factory_db
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
    driver: local